# -*- Mode: HTML -*-
<p>Built from <a href="ftp://ftp.mozilla.org/pub/firefox/candidates/39.0b5-candidates/build1/source/firefox-39.0b5.source.tar.bz2">firefox-39.0b5.source.tar.bz2</a></p>
<p>AB3E9026BE1432AC290A4DF584857EF5E8FC4CC715D1465704613F627E60F0C7C5D3AA796AE62C992CD277A3AC78AEC03ACFAB79FC41D150231EAA8D0230A79D</p>
<p>Get Cyberfox source code <a href="https://github.com/InternalError503/cyberfox-beta">https://github.com/</a></p>
