# -*- Mode: HTML -*-
<p>Built from <a href="ftp://ftp.mozilla.org/pub/firefox/candidates/45.0b1-candidates/build1/source/firefox-45.0b1.source.tar.xz">firefox-45.0b1.source.tar.xz</a></p>
<p>CE2BF5EC3BEA4BC2C95658E901F018C61238BF12FC41EC6F808D5E74925F89F61F97B6E439D9B3397FC940210C6B3A3F93D67CE865B8DDBD8F384771876CBDEC</p>
<p>Get Cyberfox source code <a href="https://github.com/InternalError503/cyberfox-beta">https://github.com/</a></p>
